Mark envelope as confirmed when it was received from a mail server
status-im/status-go pull request #1378
Opened 2019-02-18 11:07 UTC by dshulyak

Previously i didn't take into account that envelope might get delivered from a mail server faster then it is sent to it. For example, if we are connected with 2 peers, A and B. A is a mail server. B also connected with a mail server. In rare circumstances A will receive envelope from B and deliver it to us. Whisper will mark such envelope as "known" and will never try to re-deliver it to A.

This change is linked to a custom branch in our whisper repository. I will make a new whisper release once corresponding change is merged.

2019-02-18 11:07 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 867f3147 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1378/1/) | 2019-02-18 11:07:58 | ~13 sec | `linux` | [:page_facing_up: log](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1378/1/consoleText) |

2019-02-18 11:31 UTC, mandrigin requested changes
2 small things, looks good otherwise

2019-02-18 11:31 UTC, mandrigin commented on Gopkg.toml
> +  branch = "env-received-event"
just to mark that that it should be replaced by a tagged version

2019-02-18 11:31 UTC, mandrigin commented on services/shhext/tracker.go
> +		fmt.Println("received event")
looks like a leftover

2019-02-18 14:08 UTC, adambabik commented
> For example, if we are connected with 2 peers, A and B. A is a mail server. B also connected with a mail server. In rare circumstances A will receive envelope from B and deliver it to us. Whisper will mark such envelope as "known" and will never try to re-deliver it to A.

I don't quite get this. Why does it matter whether a peer is a mail server or not? From Whisper perspective it does not matter, we will receive messages from both when being connected.

> In rare circumstances A will receive envelope from B and deliver it to us.

I wouldn't say it's rare. It's perfectly normal scenario. Do we assume anything about to how many and what kind of peers we are connected when dealing with confirmations?

2019-02-18 15:03 UTC, dshulyak commented
> I don't quite get this. Why does it matter whether a peer is a mail server or not? From Whisper perspective it does not matter, we will receive messages from both when being connected.

it matters because we want to receive a confirmation from a mail server. in normal circumstances we send an envelope to all peers, and wait for a mail server to send us a special confirmation (because it won't resend an envelope).

> I wouldn't say it's rare. It's perfectly normal scenario. 

our node is the original sender of an envelope in this example. thats why i said that this is rare. basically X -> B -> A -> X was delivered faster then X -> A. it is not that common. 
(X is the original sender)

> Do we assume anything about to how many and what kind of peers we are connected when dealing with confirmations?

we assume that we are connected with at least one mail server.

2019-02-18 19:43 UTC, adambabik commented
@dshulyak thanks for the explanation! All clear now.

2019-02-20 12:15 UTC, mandrigin approved these changes
Great!

2019-02-20 16:22 UTC, mandrigin commented
@adambabik @PombeirP @cammellos can you help reviewing it? It would be awesome to have it in a new status-go release for status-react.

2019-02-20 16:22 UTC, mandrigin commented
cc @gravityblast

2019-02-20 16:51 UTC, pedropombeiro approved these changes

2019-02-20 17:11 UTC, merged