Publish rlp.RawValue instead of envelope
status-im/status-go pull request #1459
Opened 2019-05-08 11:51 UTC by cammellos

As part of a performance profiling of mailserver we noticed that most of
the resources on a query are spend decoding the whisper envelope.

This PR changes the way we store envelopes encoding the Topic into the
database key, so we can check that and we are able to publish the
envelope rawValue if it matches.

The change is backward compatible as only newly added envelopes will
have the new key, while old ones will have to be unmarshaled.

This is the first performance optimization, seems like that even if we go for postgres, we might want to allow users to use leveldb as well, as it's easier to setup (no setup required), so this is worth doing in any case.
We will only be able to see any improvement after 24hours of data have been saved (i.e there's no migration).

Currently deployed on `eth.test` if anyone wants to make some tests

2019-05-08 11:55 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (6)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 3aeb92fc | [#1](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-1459/1/) | 2019-05-08 11:55:25 | ~3 min | `ios` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-ios-190508-115131-3aeb92.zip) |
| :heavy_check_mark: | 3aeb92fc | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1459/1/) | 2019-05-08 12:12:29 | ~20 min | `linux` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-190508-115132-3aeb92.zip) |
| :heavy_check_mark: | 3aeb92fc | [#1](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1459/1/) | 2019-05-08 12:17:50 | ~26 min | `android` | [:package: aar](https://status-go.ams3.digitaloceanspaces.com/status-go-android-190508-115129-3aeb92.aar) |
| | | | | | | |
| :heavy_check_mark: | b7a34de0 | [#2](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1459/2/) | 2019-05-09 09:55:18 | ~44 sec | `linux` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-190509-095434-b7a34d.zip) |
| :heavy_check_mark: | b7a34de0 | [#2](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-1459/2/) | 2019-05-09 09:57:34 | ~3 min | `ios` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-ios-190509-095433-b7a34d.zip) |
| :heavy_check_mark: | b7a34de0 | [#2](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1459/2/) | 2019-05-09 09:58:51 | ~4 min | `android` | [:package: aar](https://status-go.ams3.digitaloceanspaces.com/status-go-android-190509-095428-b7a34d.aar) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f4272890 | [#3](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1459/3/) | 2019-05-09 10:03:45 | ~46 sec | `linux` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-190509-100258-f42728.zip) |
| :heavy_check_mark: | f4272890 | [#3](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-1459/3/) | 2019-05-09 10:05:43 | ~2 min | `ios` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-ios-190509-100257-f42728.zip) |
| :heavy_check_mark: | f4272890 | [#3](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1459/3/) | 2019-05-09 10:07:27 | ~4 min | `android` | [:package: aar](https://status-go.ams3.digitaloceanspaces.com/status-go-android-190509-100256-f42728.aar) |
| | | | | | | |
| :heavy_check_mark: | 3cd6fe34 | [#4](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-1459/4/) | 2019-05-09 10:20:45 | ~3 min | `ios` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-ios-190509-101708-3cd6fe.zip) |
| :heavy_check_mark: | 3cd6fe34 | [#4](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1459/4/) | 2019-05-09 10:25:32 | ~8 min | `linux` | [:package: zip](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-190509-101709-3cd6fe.zip) |
| :heavy_check_mark: | 3cd6fe34 | [#4](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1459/4/) | 2019-05-09 10:27:45 | ~10 min | `android` | [:package: aar](https://status-go.ams3.digitaloceanspaces.com/status-go-android-190509-101706-3cd6fe.aar) |

2019-05-08 12:12 UTC, ghost commented
<!--prchecklist--> 
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?

2019-05-08 14:12 UTC, dshulyak approved these changes

2019-05-08 16:35 UTC, mandrigin requested changes
In general, the code looks good. I'd love to see a few changes though, to improve readability.

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +	if len(cursor) == DBKeyLength || len(cursor) == DBKeyLength-whisper.TopicLength {
I'd leave old length as `DBKeyLengthLegacy` constant with a comment.

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +			envelopeBloom = whisper.TopicToBloom(whisper.BytesToTopic(key[timestampLength+common.HashLength:]))
can we have a `Topic()` method in `DBKey` struct to make this part a bit more readable?

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +		var envelopeBloom []byte
I would move this declaration right before `if len(key).....`

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +			var envelope whisper.Envelope
maybe extract a method like `envelopeBloom = extractTopicFromEncodedEnvelope(rawValue)`

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +		lastEnvelopeHash = common.BytesToHash(key[timestampLength : common.HashLength+timestampLength])
again, a method like `DBKey.EnvelopeHash()` to hide this bytes array indexing.

2019-05-08 16:35 UTC, mandrigin commented on mailserver/mailserver.go
> +func (s *WMailServer) sendEnvelopes(peer *whisper.Peer, envelopes []rlp.RawValue, batch bool) error {
`sendRawEnvelopes`?

2019-05-08 16:35 UTC, mandrigin commented on services/shhext/api.go
> +	if len(cursor) > 0 && len(cursor) != mailserver.DBKeyLength && len(cursor) != mailserver.DBKeyLength-whisper.TopicLength {
again, having a constant for the old `DBKeySize` will be useful here

2019-05-09 10:05 UTC, cammellos commented
@mandrigin ready to be reviewed again, thanks!

2019-05-09 10:10 UTC, mandrigin approved these changes
lgtm now

2019-05-09 10:58 UTC, merged