Update Makefile
status-im/status-go pull request #1926
Opened 2020-04-02 07:55 UTC by adambabik

This change fixes `setup-dev` target.

2020-04-02 07:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 479dd329 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-1926/1/) | 2020-04-02 07:57:04 | ~1 min | `linux` | [:package:`zip`](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-200402-075556-479dd3.zip) |

2020-04-02 08:33 UTC, jakubgs commented on Makefile
>  setup-build: lint-install release-install gomobile-install ##@other Prepare project for build
Is this even necessary anymore?

2020-04-02 08:34 UTC, jakubgs requested changes
Fails for me:
```
 > make setup-dev
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint bash -s -- -d -b /bin v1.21.0
golangci/golangci-lint info checking GitHub for tag 'v1.21.0'
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/v1.21.0
golangci/golangci-lint info found version: 1.21.0 for v1.21.0/linux/amd64
golangci/golangci-lint debug downloading files into /tmp/tmp.huS0uoGPHX
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-linux-amd64.tar.gz
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-checksums.txt
install: cannot create regular file '/bin/golangci-lint': Permission denied
make: *** [Makefile:290: lint-install] Error 1
```

2020-04-02 09:01 UTC, adambabik commented on Makefile
>  setup-build: lint-install release-install gomobile-install ##@other Prepare project for build
Jenkins still uses it.

2020-04-02 09:03 UTC, adambabik commented
@jakubgs hm so `GOPATH` is actually required still. In my case, I have `GOPATH` and it writes to `/Users/adamb/go/bin/golangci-lint`. In your case, you don't have it and it tries to write it to `/bin/golangci-lint`. Should we bring requirement of having `GOPATH` in the docs?

2020-04-02 12:53 UTC, jakubgs commented
Adding another step in docs is ugly. Don't newer versions of Go just default to `~/go`?
```
 > go env | grep GOPATH
GOPATH="/home/sochan/go"
```
They do. Then just do `GOPATH ?= $HOME/go` somewhere at the top of the `Makefile` so it default to that if `GOPATH` is not set(that's what `?=` does).

2020-04-02 12:56 UTC, jakubgs commented
Btw, please fix the shebang in `_assets/scripts/install_deps.sh`, it should be:
```
#!/usr/bin/env bash
```

2020-04-04 17:04 UTC, adambabik commented
@jakubgs updated

2020-04-05 15:01 UTC, jakubgs approved these changes
LGTM!

2020-04-06 07:54 UTC, merged