[#11046] Add local contact names
status-im/status-go pull request #2023
Opened 2020-08-20 14:07 UTC by flexsurfer

added nickname to contacts table and sync contact if nickname has changed

2020-08-20 14:10 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 26bc18a1 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2023/1/) | 2020-08-20 14:10:52 | ~2 min | `linux` | [:package:`zip`](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-200820-140805-26bc18.zip) |

2020-08-24 08:08 UTC, cammellos requested changes
looks good, just maybe adding test.
Also I would probably rename `nickname` to `localName` or `localContactName` (something so it's clear that is set locally, rather than remotely), but not sure what a good name would be

2020-08-24 08:08 UTC, cammellos commented on protocol/messenger.go
> +	if m.isNewContact(contact) || m.isNicknameHasChanged(contact) {
`hasNicknameChanged` is probably a better name

2020-08-24 08:08 UTC, cammellos commented on protocol/message_handler.go
> +		contact.Nickname = message.Nickname
Could you also update the tests (there should be one in `messenger_installations_test.go`) in order to make sure the nickname is also synced?

2020-08-25 12:03 UTC, Samyoul submitted a review, later dismissed
Great work @flexsurfer ! You're really doing some great stuff in `status-go`.

This PR looks great, the only suggestion I'd make is to rename references to `Nickname` to `LocalNickname` to communicate that the nickname is only for the local user.

In the case that we implement display names we want to make a clear distinction between the two.

Alternatively add some documentation to the code to make explicit that the nickname is for local purposes.

2020-08-27 08:23 UTC, flexsurfer commented
@cammellos, @Samyoul thanks, addressed all comments

2020-08-27 08:28 UTC, cammellos approved these changes
Good job! just added a suggestion

2020-08-27 08:28 UTC, cammellos commented on protocol/messenger_installations_test.go
> +	s.Require().True(actualContact.LocalNickname == "Test Nickname")
```suggestion
	s.Require().Equal("Test Nickname", actualContact.LocalNickname)
```

2020-09-07 09:34 UTC, merged

2020-09-08 13:01 UTC, Samyoul commented
@flexsurfer Great work. Congrats on the merge.

I think that this functionality would also need an update to the specs, probably in [payloads syncinstallationcontact](https://github.com/status-im/specs/blob/master/docs/stable/6-payloads.md#syncinstallationcontact)