Resend emoji reactions when expired
status-im/status-go pull request #2088
Opened 2020-12-02 11:36 UTC by vkjr

A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #

2020-12-02 11:39 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6c2f06a4 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2088/1/) | 2020-12-02 11:39:22 | ~2 min | `linux` | [:package:`zip`](https://status-go.ams3.digitaloceanspaces.com/status-go-desktop-201202-113711-6c2f06.zip) |

2020-12-08 17:19 UTC, cammellos requested changes
Overall looks really good!
One thing I would change, is that currently we resend all of them on `resendExpiredEmojiReactions`, and we don't wait for some backoff time.

So instead of re-sending them on `Start` or on `Expired`, I would start a go-routine in a loop, sleeping at interval (say 1s), and when it wakes up run `resendExpiredEmojiReactions`.
We also want to space the retries, say first retry at 30s, second at 60s, then 120s. 
It's a pattern we use already in the codebase, I can show you exactly where, we can have a chat tommorrow.
Other than that looks all really good!

2020-12-10 15:00 UTC, vkjr commented
@camellos, changes made to PR:
- `LastSent` field now sets in `RawMessage` on sending
- `watchExpiredEmojis()` resends emojis once in a second
- `shouldResendEmojiReaction()` implements condition that permits resending emoji only after more and more time passes. 

We were also discussing that information about message expiration can be ignored but I checked its implementation and found that it is not related to receiving acknowledgement, so it is quite reliable so Expired still used to fetch less records from DB. wdyt?

2020-12-11 10:50 UTC, vkjr commented
@cammellos, got rid of expired field in favor of using `Sent` and `SendCount`

2020-12-14 08:02 UTC, cammellos reviewed
Looks good, just a few minor comments about `getTimesource` but otherwise all good!

2020-12-14 08:02 UTC, cammellos commented on protocol/messenger.go
> +	backoffElapsed := time.Now().After(time.Unix(int64(message.LastSent), 0).Add(backoff))
Here you probably want to pass a `TimeSource`, which is an `NTP` synced time, otherwise you might have inconsistencies if the clock of the user is skewed.
in messenger you can just pass as an argument:
`shouldSendEmojiReaction(message, m.getTimesource())`
and then call `t.getCurrentTime()` which returns the current time in unix milliseconds, so you can make this comparison using only `ints`

2020-12-14 08:02 UTC, cammellos commented on protocol/messenger.go
> +	spec.LastSent = uint64(time.Now().Unix())
Same here, you probably want to use `m.getTimesource` so it's NTP synchronize

2020-12-14 13:11 UTC, cammellos approved these changes
Great job!

2020-12-15 14:43 UTC, merged