[WIP] add PinMessage and PinnedMessage
status-im/status-go pull request #2180
Opened 2021-03-24 21:32 UTC by gravityblast

A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #

2021-03-24 21:34 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | f2c8ea5d | [#1](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-2180/1/) | 2021-03-24 21:34:18 | ~1 min | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-2180/1/consoleText) |

2021-03-29 15:02 UTC, cammellos reviewed
first pass, some comments :)

2021-03-29 15:02 UTC, cammellos commented on protocol/message_handler.go
> +	chat.Active = false
This does not look right, it might hide the chat whenever a pinned message is received

2021-03-29 15:02 UTC, cammellos commented on protocol/message_persistence.go
> +			if existingTimestamp < message.Timestamp {
We tend to use `Clock` and not timestamp, as timestamp can result in some issues of consistency, while clock is a logical clock

2021-03-29 15:02 UTC, cammellos commented on protocol/messenger_pin_messages.go
> +	m.mutex.Lock()
I think `SentPinMessage` is probably enough, I don't think status-react will need to pin multiple messages in a single RPC call, so maybe we don't need to have it

2021-03-29 15:02 UTC, cammellos commented on protocol/messenger_pin_messages.go
> +	response.PinMessages = []*common.PinMessage{message}
We might want to use the `AddPinnedMessage` pattern on `response`, as that's what we are moving towards

2021-03-29 15:02 UTC, cammellos commented on protocol/messenger_pin_messages.go
> +	// response.Messages, err = m.pullMessagesAndResponsesFromDB([]*common.Message{message})
I don't think so

2021-03-29 15:02 UTC, cammellos commented on protocol/messenger_response.go
> +func (r *MessengerResponse) overridePinMessages(messages []*common.PinMessage) {
Here we might want to use the patter we use with communities, so instead of an array use a `map`, as eventually we'd like to have them all using the same

2021-04-13 19:00 UTC, jrainville commented
I tried to build this branch to start implementing pinned messages in Desktop, but I get the following build error:
```
 github.com/status-im/status-go/services/ext
services/ext/api.go:487:2: not enough arguments to return
services/ext/api.go:487:30: api.service.messenger.SendPinMessages undefined (type *"github.com/status-im/status-go/protocol".Messenger has no field or method SendPinMessages)
make[1]: *** [Makefile:143: statusgo-shared-library] Error 2
```

Also, question relative to the API: to add a pinned message, I have to call `SendPinMessage`? If so, what are the arguments I need to pass, I didn't understand well from the code.

Finally, is there a way to unpin a message?

2021-04-13 20:46 UTC, briansztamfater commented
> I tried to build this branch to start implementing pinned messages in Desktop, but I get the following build error:
> 
> ```
>  github.com/status-im/status-go/services/ext
> services/ext/api.go:487:2: not enough arguments to return
> services/ext/api.go:487:30: api.service.messenger.SendPinMessages undefined (type *"github.com/status-im/status-go/protocol".Messenger has no field or method SendPinMessages)
> make[1]: *** [Makefile:143: statusgo-shared-library] Error 2
> ```
> 
> Also, question relative to the API: to add a pinned message, I have to call `SendPinMessage`? If so, what are the arguments I need to pass, I didn't understand well from the code.
> 
> Finally, is there a way to unpin a message?

I got the same results while building for mobile but now with the latest changes the build succeeded. Try again with the latest changes and the build will probably pass!

2021-04-14 08:34 UTC, gravityblast commented
@jrainville I pushed a commit to fix the build problem and added more info in the description about the message structure and how to pin/unpin.

2021-04-14 13:51 UTC, jrainville commented
I confirm that it builds now. Thanks for that and the new info in the description 💯

2021-04-15 08:30 UTC, gravityblast commented
@jrainville @briansztamfater I forced-pushed after a rebase to have all the new changes from `develop`.

2021-04-15 10:55 UTC, Samyoul requested changes

2021-04-15 10:55 UTC, Samyoul commented on protocol/message_persistence.go
> +	return result, newCursor, nil
The `cursors` slice maybe nil at this point, as there is no check on the slice's state.

```suggestion
	if len(result) > limit  && cursors != nil  {
		newCursor = cursors[limit]
		result = result[:limit]
	}
	return result, newCursor, nil
```

2021-04-15 10:55 UTC, Samyoul commented on protocol/messenger_pin_message_test.go
> +}
The `MessengerPinMessageSuite` provides the `types.Waku` via `s.shh`, so the `shh` parameter is never used

```suggestion
func (s *MessengerPinMessageSuite) newMessenger() *Messenger {
	privateKey, err := crypto.GenerateKey()
	s.Require().NoError(err)

	messenger, err := newMessengerWithKey(s.shh, privateKey, s.logger, nil)
	s.Require().NoError(err)
	return messenger
}
```

2021-04-15 10:55 UTC, Samyoul commented on protocol/messenger_pin_messages.go
> +		return nil, errors.New("Chat not found")
Tiny little thing, go convention is not to start an error message with a capital letter.

```suggestion
		return nil, errors.New("chat not found")
```

2021-04-15 10:57 UTC, Samyoul approved these changes
There only minor things that I spotted.

2021-04-15 11:20 UTC, gravityblast commented
thank you @Samyoul , I'm going to check your comments and update the code

2021-04-15 17:15 UTC, jrainville commented
@gravityblast I think the `SendPinMessage` api is missing the `ChatId` property. I couldn't call that API until I manually hardcoded my chatId in the go file. The API seems to only have the localChatId, but not the ChatId.

2021-04-15 17:37 UTC, jrainville commented
Also, is it possible that `pinnedMessageByChatID` is not part of the API? I don't see it in api.go and also, I get `the method wakuext_pinnedMessageByChatID does not exist/is not available`

2021-04-15 22:02 UTC, gravityblast commented
@jrainville sorry I though you had access to messageByChatID, but I see the right API should be `ChatMessages`.
so I added now `ChatPinnedMessages`, that you should see as `wakuext_chatPinnedMessages`

2021-04-15 22:09 UTC, gravityblast commented
> @gravityblast I think the SendPinMessage api is missing the ChatId property. I couldn't call that API until I manually hardcoded my chatId in the go file. The API seems to only have the localChatId, but not the ChatId.

@jrainville does it work if you call it `chat_id`? I see it's auto generated by protobuf

2021-04-16 14:17 UTC, jrainville commented
@gravityblast Cool, both work now. Thanks!

2021-04-19 16:50 UTC, cammellos commented
@gravityblast @briansztamfater I have attempted a rebase here https://github.com/status-im/status-go/tree/feature/pinned-messages-2 if you want to use it for the time being (I just made sure it compiles but haven't checked much more)

I have updated the timestamp of the migration as now in develop there's a couple of newer ones and this one needs to come last.

2021-04-19 19:07 UTC, jrainville commented
Everything works very well now, but it seems like there is no signal when there is a pin (or unpin) that is sent. I receive a signal with the chat and the last message, but it doesn't specify `pinned` or anything relative to that.

It would be super helpful if when a pin or unpin was done, it would send a message signal with the `pinned` flag update in it.

Let me know if it's doable. Thanks!

2021-04-20 13:12 UTC, gravityblast commented
@cammellos I also rebased and forced pushed here, /cc @briansztamfater @jrainville

2021-04-20 13:15 UTC, gravityblast commented
@jrainville ok I'll update it to send a signal as well

2021-04-22 20:23 UTC, briansztamfater commented
@gravityblast @jrainville  Not sure but thinking about edge cases, I'm wondering if we have a very old pinned message that is not loaded in the chat, we would also need to load the reactions for that specific message. Do we have any API method to get reactions for specific messageId(s)?

2021-04-23 14:09 UTC, jrainville commented
As far as I can see, that API doesn't exist. 
You raise a good point. That API could be useful.
However, I wonder what happens if the message and pin is very old (more than one month), you wouldn't be able to fetch it in the first place right?

2021-04-23 15:39 UTC, gravityblast commented
yes for now if you don't have the message itself we can't see it as a pinned message.
we can start with this and then see if we need some changes

2021-05-10 14:52 UTC, jrainville commented
Tested the latest commit on desktop and everything works now. Signals, fetching, pinning and unpining all work in 1-1 chats and group chats.

Can't wait for this to be merged 🙌

2021-05-14 21:22 UTC, merged