feat: auto message
status-im/status-go pull request #2441
Opened 2021-11-24 14:18 UTC by alaibe

Send message every 2 minutes to status-bot chat id

2021-11-24 14:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6b1c56d7 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2441/1/) | 2021-11-24 14:21:27 | ~3 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-211124-141820-6b1c56-pr2441.zip) |

2021-11-24 15:29 UTC, richard-ramos approved these changes

2021-11-24 15:33 UTC, cammellos requested changes
Just to understand, is this only for testing? 
We have a bot already that is sending as an external command, we could expand that one.
In `cmd/ping-community`

2021-11-24 17:33 UTC, alaibe commented
@cammellos yes, this is for testing,this is related to our last call where we want each desktop user to have a flag that if enable, that will push a message every tick to a channel. At least this is what I understood.

I tried to see if i could reuse the command but as this should be started based on the flag I couldn t find a way to reuse the ping command, maybe I missed something, feel free to indicate me what I could do better

2021-11-25 14:01 UTC, cammellos reviewed
I think it needs a bit of error handling, otherwise looks good

2021-11-25 14:01 UTC, cammellos commented on protocol/messenger_auto_message.go
> +		m.logger.Error("[auto message] failed to start auto message loop", zap.Error(err))
I would make it return an error, this might indicate an actual problem (db is closed etc)

2021-11-25 14:01 UTC, cammellos commented on protocol/messenger_auto_message.go
> +					m.logger.Error("[auto message] failed to send message", zap.Error(err))
You might want `continue` here, otherwise i'ts likely to panic

2021-11-26 10:09 UTC, cammellos approved these changes

2021-11-26 10:09 UTC, cammellos commented on protocol/messenger_auto_message.go
> +					m.logger.Error("[auto message] failed to mark message as delivered", zap.Error(err))
Do you want to send a signal even if this fails? or is it better to continue in this case?

2021-11-29 13:11 UTC, merged