[13587] Change local notifcation text
status-im/status-go pull request #2747
Opened 2022-07-10 07:22 UTC by ibrkhalil

Closes status-react #13587

2022-07-10 07:25 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d3d6e3b5 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2747/1/) | 2022-07-10 07:25:07 | ~2 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-220710-072239-d3d6e3-pr2747.zip) |

2022-07-27 12:52 UTC, richard-ramos requested changes

2022-07-27 12:52 UTC, richard-ramos commented on protocol/local_notifications.go
> +		Message:  n.Contact.CanonicalName() + " add you to group " + n.Chat.Name,
```suggestion
		Message:  n.Contact.CanonicalName() + " added you to group " + n.Chat.Name,
```

2025-07-01 12:33 UTC, closed without merging

2025-07-01 12:33 UTC, igor-sirotin commented
Closing as duplicate of https://github.com/status-im/status-go/pull/2909