feat(communities): Send signal when request to join was declined
status-im/status-go pull request #2925
Opened 2022-10-26 16:26 UTC by borismelnik

Add declined requests to message response.

Important changes:
- [x] Something worth noting for reviewers.

2022-10-26 16:26 UTC, ghost commented
<!--prchecklist--> 
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

2022-10-26 16:29 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 38366044 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2925/1/) | 2022-10-26 16:29:21 | ~2 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-221026-162634-383660-pr2925.zip) |

2022-10-26 16:38 UTC, cammellos requested changes
@borismelnik not sure it's a good idea to explicitly decline requests from users.
The reason is that they are used as a spam vector, so dismiss them should be effortless for the most part for the community owner.
We had the same problem in the past with private group chats, where a spammer would send thousands of requests, and the user would be answering them, generating traffic and being a slow operation in general.
This is consistent with what we do with contact requests, no notification on the other end that their request has been declined, I think it would be safer until better spam protection is in place.
cc @John-44

2022-10-26 16:38 UTC, cammellos commented on protocol/communities/manager.go
> +	community, err := m.GetByID(dbRequest.CommunityID)
Why are you saving the community? I can't see any changes to it

2022-10-26 16:38 UTC, cammellos commented on services/ext/api.go
> +// MyDeclinedRequestsToJoin returns the pending requests for the logged in user
pending?

2022-10-26 19:00 UTC, borismelnik commented on services/ext/api.go
> +// MyDeclinedRequestsToJoin returns the pending requests for the logged in user
sorry :)

2022-10-27 08:28 UTC, borismelnik commented
> @borismelnik not sure it's a good idea to explicitly decline requests from users.
> The reason is that they are used as a spam vector, so dismiss them should be effortless for the most part for the community owner.
> We had the same problem in the past with private group chats, where a spammer would send thousands of requests, and the user would be answering them, generating traffic and being a slow operation in general.
> This is consistent with what we do with contact requests, no notification on the other end that their request has been declined, I think it would be safer until better spam protection is in place.
> cc @John-44

Repeating requests is blocking from our side. If it make sense, I can add a code to blocking request when it was declined. Wdyt? @cammellos @John-44

2022-10-27 08:35 UTC, cammellos commented
> > @borismelnik not sure it's a good idea to explicitly decline requests from users.
> > The reason is that they are used as a spam vector, so dismiss them should be effortless for the most part for the community owner.
> > We had the same problem in the past with private group chats, where a spammer would send thousands of requests, and the user would be answering them, generating traffic and being a slow operation in general.
> > This is consistent with what we do with contact requests, no notification on the other end that their request has been declined, I think it would be safer until better spam protection is in place.
> > cc @John-44
> 
> Repeating requests is blocking from our side. If it make sense, I can add a code to blocking request when it was declined. Wdyt? @cammellos @John-44

Not sure I understand fully, but the easiest vector of attack for a spammer is to sent 100s of requests, each from a different account, so blocking the user would not help in that case, if that's what you were suggesting, but I might have misunderstood.

2022-10-27 08:45 UTC, borismelnik commented
> > > @borismelnik not sure it's a good idea to explicitly decline requests from users.
> > > The reason is that they are used as a spam vector, so dismiss them should be effortless for the most part for the community owner.
> > > We had the same problem in the past with private group chats, where a spammer would send thousands of requests, and the user would be answering them, generating traffic and being a slow operation in general.
> > > This is consistent with what we do with contact requests, no notification on the other end that their request has been declined, I think it would be safer until better spam protection is in place.
> > > cc @John-44
> > 
> > 
> > Repeating requests is blocking from our side. If it make sense, I can add a code to blocking request when it was declined. Wdyt? @cammellos @John-44
> 
> Not sure I understand fully, but the easiest vector of attack for a spammer is to sent 100s of requests, each from a different account, so blocking the user would not help in that case, if that's what you were suggesting, but I might have misunderstood.

Yes, you got it correctly :) but anyway, the spammer is able to send 100 requests even if he didn't get notification.

2022-12-07 18:46 UTC, jrainville commented
@cammellos I'd like to clarify some points here.

Right now, spammers could create accounts and request to access a community. The admin can only ignore them and it's annoying.

If we merge this PR, what changes? One more broadcast of the denied request, right?

Was there a conversation offline? I heard that maybe we wanted to wait for the captcha before merging this?

@borismelnik what is the advantage of merging this vs doing what @cammellos is suggesting; ie just dismissing the request?
Do we really want the person requesting access to know they have been refused? Maybe that last question is more for designers.

2022-12-07 18:55 UTC, cammellos commented
> If we merge this PR, what changes? One more broadcast of the denied request, right?

Correct, and also the admin need to make way more effort in terms of resources to deny the request (transferring data over the wire is way more costly than just making an entry in the database).

I think this is the kind of stuff that doesn't matter for the most part, most of the times, honest people will not be denied access to a community (spammers though will for sure), so it's just useful in a very small subset of cases, and costly/useless in more common scenarios.

The way we handle this, is that a user can re-request access after 1 day or so (client side check), if the admin has already a pending request, it will just be ignored, otherwise it will be shown again. That works fine, I had a conversation with John about this and he was ok with this solution.

2022-12-07 19:06 UTC, jrainville commented
Ok makes sense. Thanks for the explanation.

Do you recommend we just drop this PR/feature or wait for a captcha, @cammellos ?

2022-12-08 10:59 UTC, cammellos commented
@jrainville I think this is not needed, yes, captcha we also need to have a conversation, we could schedule a meeting to discuss it if you'd like?

2022-12-08 14:53 UTC, jrainville commented
> we could schedule a meeting to discuss it if you'd like?

2022-12-08 14:54 UTC, jrainville commented
> we could schedule a meeting to discuss it if you'd like?

@cammellos yeah. Do you want John to be there to discuss the requirements? Or you want it more for the software part?

2022-12-08 14:56 UTC, cammellos commented
> > we could schedule a meeting to discuss it if you'd like?
> 
> @cammellos yeah. Do you want John to be there to discuss the requirements? Or you want it more for the software part?

No need for John, it's more on the technical side, since we don't know if hcaptcha will do more good than harm

2022-12-08 14:59 UTC, jrainville commented
@cammellos ok perfect. You can schedule the meeting whenever you have time. Any time after 9am EST is good with me.
You can invite whoever you feel appropriate. Add Boris too, he'll probably be the one doing it on our side since he did all the new community join flow.

2023-01-11 15:52 UTC, closed without merging