fix(community): don't delete chat and messages when leaving community
status-im/status-go pull request #3006
Opened 2022-12-06 20:10 UTC by jrainville

This creates a smoother experience for users when they leave a community since they can see the exact same messages they had before without having to rely on the mailserver.

To make it work on the desktop or mobile, side you need to make sure that you re-fetch the messages for the channels when re-joining (or re-spectating). This might require to reset the cursor.

2022-12-06 20:12 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | ceb6c051 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-3006/1/) | 2022-12-06 20:12:32 | ~1 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-221206-201107-ceb6c0-pr3006.zip) |

2022-12-06 20:35 UTC, cammellos requested changes
I think this one might leave the chats active, so that you'd be still fetching messages etc (on next login for example).
We have `deactivateChat` that sets the chat to inactive, and that could be used, also I think we should add a few tests to validate the behavior.

2022-12-06 21:39 UTC, jrainville commented
Good point @cammellos . I added the call to `deactivateChat`. I had to add a new argument so that we can select if we want the history to be cleared. 
I'll add the tests tomorrow morning.

2022-12-07 19:36 UTC, jrainville commented
@cammellos ready for review.
I updated the `TestLeaveAndRejoinCommunity` to check the number of active chats after leave and then after rejoin

2022-12-09 16:17 UTC, richard-ramos approved these changes

2022-12-09 16:44 UTC, cammellos approved these changes

2022-12-09 19:43 UTC, merged