feat(CommunityTokens): Keep community token details in database
status-im/status-go pull request #3190
Opened 2023-02-14 10:37 UTC by endulab

Keep community token details in database:
- new table for community tokens
- API for get, add, update community token.

Issue #9233

2023-02-14 10:39 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 165ffc5a | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-3190/1/) | 2023-02-14 10:39:24 | ~1 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-230214-103805-165ffc-pr3190.zip) |

2023-02-20 12:52 UTC, endulab commented
@0x-r4bbit @richard-ramos please review

2023-02-20 19:09 UTC, jrainville approved these changes
LGTM

2023-02-21 07:58 UTC, 0x-r4bbit approved these changes

2023-02-24 12:51 UTC, richard-ramos requested changes, later dismissed
Migration timestamp needs to be updated

2023-02-27 09:37 UTC, merged