Fix delete for me
status-im/status-go pull request #3732
Opened 2023-07-09 15:06 UTC by ibrkhalil

Using localChatId didn't work for delete-for-me, Using chatId works.
Closes #16467 on status-mobile

2023-07-09 15:09 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1fb8b2b8 | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-3732/1/) | 2023-07-09 15:09:43 | ~2 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-230709-150647-1fb8b2-pr3732.zip) |

2023-07-10 07:00 UTC, cammellos requested changes
I think this will likely break things, since `albumMessages` is used in 3 places at least, did you verify it's not breaking anything? (unfortunately those places are not covered by test it looks like)
Also this should come with a test

2023-07-10 10:05 UTC, cammellos approved these changes

2023-07-10 10:10 UTC, borismelnik approved these changes
👍

2023-07-10 13:50 UTC, ilmotta approved these changes

2023-07-10 19:26 UTC, merged