fix: sync community request decision
status-im/status-go pull request #4190
Opened 2023-10-24 12:23 UTC by qfrank

This PR primarily addresses the synchronization of community request decisions for notifications.

Closes [mobile issue](https://github.com/status-im/status-mobile/pull/17600#issuecomment-1759194367)

2023-10-24 12:29 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 29d141b4 | [#1](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-4190/1/) | 2023-10-24 12:29:15 | ~5 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-231024-122359-29d141-pr4190.zip) |

2023-10-25 13:05 UTC, igor-sirotin requested changes
Hmmmm. I don't understand why do we need to have a special `SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION` message. Wasn't all this refactor about making the notifications logic-driven?

We already have `SYNC_CONTACT_REQUEST_DECISION` message.
I think we should be able to update the notification basing on the contact request state itself, WDYT?

_____

Also, I'm a bit confused I guess you meant CONTACT, not COMMUNITY?
There's "community request decision" all over the code, but the PR title mentiones contact 🙂

2023-10-25 13:16 UTC, qfrank commented
> Hmmmm. I don't understand why do we need to have a special `SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION` message. Wasn't all this refactor about making the notifications logic-driven?
> 
> We already have `SYNC_CONTACT_REQUEST_DECISION` message. I think we should be able to update the notification basing on the contact request state itself, WDYT?
> 
> Also, I'm a bit confused I guess you meant CONTACT, not COMMUNITY? There's "community request decision" all over the code, but the PR title mentiones contact 🙂

thank you , I mean join community request not contact request, and i didn't see PR title like you said ? can you show me your screenshot for the title on your side? 😅
when community manager received join community request from someone not joined yet, a notification produced for manager, the manager can accept or decline on the notification of join community request, and the decision will synced across other devices for the same user.

`SYNC_CONTACT_REQUEST_DECISION` is only used for contact request notification not join community request notification. @igor-sirotin

2023-10-25 13:23 UTC, igor-sirotin commented
Ok I have no idea where I saw anything about contact request 🤦 
Sorry for false alarm 😅

2023-10-25 13:26 UTC, igor-sirotin approved these changes

2023-10-26 04:17 UTC, merged