Peer syncing toggle
status-im/status-go pull request #4758
Opened 2024-02-19 16:15 UTC by alwx

A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #

2024-02-19 16:19 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 16448bcf | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-4758/1/) | 2024-02-19 16:19:08 | ~3 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240219-161553-16448b-pr4758.zip) |

2024-02-23 18:39 UTC, cammellos requested changes
Looks good for the most part, the only thing is that we don't need to sync it across devices, and some minor neatpicks on naming/parameters, great work!

2024-02-23 18:39 UTC, cammellos commented on multiaccounts/settings/columns.go
> +		syncProtobufFactory: &SyncProtobufFactory{
We don't need to sync this across installations

2024-02-23 18:39 UTC, cammellos commented on multiaccounts/settings/sync_protobuf_factories.go
> +func buildRawPeerSyncingEnabledSyncMessage(v bool, clock uint64, chatID string) (*common.RawMessage, *protobuf.SyncSetting, error) {
this can be removed as no need to sync it

2024-02-23 18:39 UTC, cammellos commented on protocol/messenger_mailserver.go
> +func (m *Messenger) TogglePeerSyncing(value bool) error {
maybe best to put it in `protocol/messenger_settings.go`
and use a `request` object

similarly to:

```
func (m *Messenger) SetLightClient(request *requests.SetLightClient) error {
	return nodecfg.SetLightClient(m.database, request.Enabled)
}
```

2024-02-26 16:28 UTC, alwx commented
@cammellos everything was fixed in the latest commit

2024-02-27 12:37 UTC, cammellos commented on protocol/protobuf/sync_settings.proto
> +    PEER_SYNCING_ENABLED = 22;
no need for this anymore

2024-02-28 14:24 UTC, cammellos commented on services/ext/api.go
> +func (api *PublicAPI) TogglePeerSyncing(value bool) error {
last thing, if you could use  `protocol/requests/toggle_peer_syncing.go`  for this,l similarly as we do for other

2024-02-29 16:05 UTC, cammellos approved these changes

2024-03-05 10:44 UTC, merged