travis: update go version
status-im/status-go pull request #507
Opened 2017-12-08 08:27 UTC by dvrkps

1.x match latest stable go version

2017-12-12 14:28 UTC, divan commented
@dvrkps thanks, I didn't know about that `1.x` wildcard. Although there is usually no risks in upgrading Go version, I think we prefer "upgrade Go version" process to be manual and explicit action.

2017-12-12 17:02 UTC, dvrkps commented
@divan 1.9.x match latest 1.9 subversion(1.9.2 today)

2017-12-14 10:32 UTC, tiabc approved these changes
Looks good. However, it's not the only place where we build go projects, we'll also need to change it in:
1. https://github.com/status-im/faucet/blob/39999d545a9185b9ab1248f635cea882c9e84692/Dockerfile#L1
2. https://github.com/status-im/status-cluster/blob/18db330d87c5c19300d454f345714d486529eccb/roles/golang/defaults/main.yml#L2
3. https://github.com/status-im/status-cluster/blob/18db330d87c5c19300d454f345714d486529eccb/group_vars/jenkins-nodes.yml#L2

2017-12-15 09:39 UTC, adambabik approved these changes

2017-12-15 09:42 UTC, adambabik commented
@tiabc these are private repos and I believe they should have a separate CI integration. Another thing is whether we should run tests on both 1.8.x and 1.9.x Go releases here...

2017-12-15 10:26 UTC, dvrkps commented
@tiabc @adambabik @divan i added 1.8.x also.

2017-12-15 15:24 UTC, adambabik requested changes

2017-12-15 15:24 UTC, adambabik commented on .travis.yml
> +- 1.8.x
As we use Build Stages it's more tricky. You can check [this issue](https://github.com/travis-ci/beta-features/issues/28) for possible solutions. We would like to run `Lint` and `Test unit and integration` on both. The rest of stages can execute on `1.9.x` only.

2017-12-19 08:12 UTC, tiabc requested changes
@adambabik @dvrkps let's just run everything on a single Go version? I can't see why we may need to run anything on 1.8 and 1.9

2017-12-19 09:45 UTC, dvrkps commented
@tiabc @adambabik single version as 1.x or 1.9.x ? 
1.x match latest stable go version

2017-12-19 11:56 UTC, adambabik commented
@dvrkps I think `1.9.x` was good. We need more control over upgrading Go version.

2017-12-19 11:56 UTC, tiabc commented
1.9.x is fine. We don't need to uncontrollably update the minor version while the patch is fine.

2017-12-19 12:06 UTC, dvrkps commented
@tiabc @adambabik done. i remove 1.8.x.

2017-12-19 12:07 UTC, adambabik approved these changes
Thanks!

2017-12-21 04:51 UTC, tiabc approved these changes
Such a long discussion and such a small changelist :)

2017-12-21 04:52 UTC, merged