Use gometalinter config instead of makefile
status-im/status-go pull request #560
Opened 2018-01-20 06:24 UTC by dnephin

Replace most of `lint.mk` with a `.gometalinter.json` to remove duplication

Closes #559

2018-01-20 10:47 UTC, adambabik requested changes
Thanks for the PR!

Unfortunately, it looks like our previous configuration was poor and many files were not linted (errors visible in Travis) :/ Before we merge this PR to develop we need to fix it. There are two options:
1. Fix code errors in this PR (but it was not within the scope of the issue),
2. Change base branch of this PR to a temporary one, merge this PR into that temporary branch and create another PR to fix the code.

Please let me know which one is the best for you.

2018-01-20 10:47 UTC, adambabik commented on .gometalinter.json
> +    "Skip": ["helpers", "static", "testing", "e2e"],
`testing` and `e2e` should be included.

2018-01-20 10:47 UTC, adambabik commented on .gometalinter.json
> +    "Enable": [
For all curious reviewers, `unused`, `staticcheck`, `gosimple` are part of `megacheck` so they are included.

2018-01-20 10:47 UTC, adambabik commented on .gometalinter.json
> +{
Can we also enable `--warn-unmatched-nolint`?

2018-01-20 10:47 UTC, adambabik commented on static/tools/mk/lint.mk
> +lint:
Could you also move `lint-install` and `lint` targets to the main `Makefile` and delete `static/tools/mk/lint.mk` completely?

2018-01-20 17:49 UTC, dnephin commented
Thanks, I'll make these changes in the next couple of days

2018-01-23 04:35 UTC, dnephin commented
I fixed the first set of lint errors, however adding `WarnUnmatchedDirective` adds another 60 errors from `nolint`.

2018-01-23 05:15 UTC, adambabik commented
@dnephin let's skip `WarnUnmatchedDirective` for now then. I will create a follow-up issue.

2018-01-24 04:42 UTC, dnephin commented
linting passed, e2e failed with a panic

2018-01-24 06:34 UTC, dshulyak approved these changes
thanks, that is known error, I restarted  a job

2018-01-24 07:39 UTC, adambabik approved these changes

2018-01-24 07:40 UTC, adambabik commented
Thanks a lot @dnephin! It's so much better now.

2018-01-24 08:25 UTC, merged