test(rpc)_: wakuext add contact
status-im/status-go pull request #5706
Opened 2024-08-13 12:53 UTC by antdanchenko

A description to understand introduced changes without reading the code.

added second instance of status-go
added test for add contact flow:

- `accounts_getAccounts` -> retrieve own public key for messaging
- each status-go instance sends a contact request to the other via  `wakuext_sendContactRequest`
- each status-go instance accepts contact request from other via `wakuext_acceptContactRequest`
- send wakuext_contacts request and verify: added == True, id == to the correct contact

 added test for wakuext_peers that uses schema as vereficatio

2024-08-13 12:56 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (23)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 46a9f9ef | [#1](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/1/) | 2024-08-13 12:56:43 | ~2 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/1//consoleText) |
| :heavy_check_mark: | 46a9f9ef | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-5706/1/) | 2024-08-13 12:58:11 | ~3 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240813-125413-46a9f9-pr5706.zip) |
| :heavy_check_mark: | 46a9f9ef | [#1](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-5706/1/) | 2024-08-13 12:58:33 | ~4 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-240813-125410-46a9f9-pr5706.zip) |
| :heavy_check_mark: | 46a9f9ef | [#1](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-5706/1/) | 2024-08-13 12:59:19 | ~5 min | `android` | [:package:`aar`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-android-240813-125409-46a9f9-pr5706.aar) |
| :heavy_check_mark: | 46a9f9ef | [#1](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/1/) | 2024-08-13 13:39:00 | ~44 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/1//consoleText) |
| | | | | | | |
| :heavy_multiplication_x: | 0cd86e40 | [#2](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/2/) | 2024-08-16 10:55:05 | ~58 sec | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/2//consoleText) |
| :heavy_check_mark: | 0cd86e40 | [#2](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-5706/2/) | 2024-08-16 10:56:24 | ~2 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240816-105402-0cd86e-pr5706.zip) |
| :heavy_check_mark: | 0cd86e40 | [#2](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/2/) | 2024-08-16 10:56:24 | ~2 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/2//consoleText) |
| :heavy_check_mark: | 0cd86e40 | [#2](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-5706/2/) | 2024-08-16 10:56:53 | ~2 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-240816-105401-0cd86e-pr5706.zip) |
| :heavy_check_mark: | 0cd86e40 | [#2](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-5706/2/) | 2024-08-16 10:59:28 | ~5 min | `android` | [:package:`aar`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-android-240816-105400-0cd86e-pr5706.aar) |
| :heavy_multiplication_x: | 0cd86e40 | [#3](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/3/) | 2024-08-16 11:11:05 | ~26 sec | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/3//consoleText) |
| :heavy_multiplication_x: | 0cd86e40 | [#4](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/4/) | 2024-08-16 11:27:08 | ~1 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/4//consoleText) |
| :heavy_multiplication_x: | 0cd86e40 | [#5](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/5/) | 2024-08-16 11:38:48 | ~1 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/5//consoleText) |
| | | | | | | |
| :heavy_multiplication_x: | b5fc6ebf | [#6](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/6/) | 2024-08-22 08:15:10 | ~1 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/6//consoleText) |
| :heavy_check_mark: | b5fc6ebf | [#3](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/3/) | 2024-08-22 08:15:59 | ~2 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/3//consoleText) |
| :heavy_check_mark: | b5fc6ebf | [#3](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-5706/3/) | 2024-08-22 08:17:10 | ~3 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-240822-081340-b5fc6e-pr5706.zip) |
| :heavy_check_mark: | b5fc6ebf | [#3](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-5706/3/) | 2024-08-22 08:17:21 | ~3 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240822-081344-b5fc6e-pr5706.zip) |
| :heavy_check_mark: | b5fc6ebf | [#3](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-5706/3/) | 2024-08-22 08:17:57 | ~4 min | `android` | [:package:`aar`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-android-240822-081339-b5fc6e-pr5706.aar) |
| | | | | | | |
| :heavy_check_mark: | df650a2a | [#4](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/4/) | 2024-08-22 09:26:13 | ~1 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/4//consoleText) |
| :heavy_check_mark: | df650a2a | [#4](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-5706/4/) | 2024-08-22 09:27:02 | ~2 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240822-092459-df650a-pr5706.zip) |
| :heavy_check_mark: | df650a2a | [#4](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-5706/4/) | 2024-08-22 09:27:40 | ~2 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-240822-092457-df650a-pr5706.zip) |
| :heavy_check_mark: | df650a2a | [#4](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-5706/4/) | 2024-08-22 09:29:11 | ~4 min | `android` | [:package:`aar`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-android-240822-092456-df650a-pr5706.aar) |
| :heavy_check_mark: | df650a2a | [#7](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/7/) | 2024-08-22 10:09:27 | ~44 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/7//consoleText) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_multiplication_x: | 3ee83536 | [#8](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/8/) | 2024-08-22 10:47:54 | ~1 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5706/8//consoleText) |
| :heavy_check_mark: | 3ee83536 | [#5](https://ci.status.im/job/status-go/job/prs/job/android/job/PR-5706/5/) | 2024-08-22 10:48:16 | ~1 min | `android` | [:package:`aar`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-android-240822-104641-3ee835-pr5706.aar) |
| :heavy_check_mark: | 3ee83536 | [#5](https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-5706/5/) | 2024-08-22 10:48:36 | ~1 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-desktop-240822-104646-3ee835-pr5706.zip) |
| :heavy_check_mark: | 3ee83536 | [#5](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/5/) | 2024-08-22 10:49:08 | ~2 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5706/5//consoleText) |
| :heavy_check_mark: | 3ee83536 | [#5](https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-5706/5/) | 2024-08-22 10:52:20 | ~5 min | `ios` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-ios-240822-104642-3ee835-pr5706.zip) |
| | | | | | | |
| :heavy_check_mark: | 42b0700c | [#6](https://ci.status.im/job/status-go/job/prs [...]

2024-08-13 19:36 UTC, glitchminer commented on integration-tests/pytest.ini
> +    waku
should be `wakuext` ?

2024-08-16 11:25 UTC, anastasiyaig approved these changes

2024-08-16 11:37 UTC, yevh-berdnyk reviewed
Only one small suggestion, otherwise LGTM!

2024-08-16 11:38 UTC, yevh-berdnyk commented on integration-tests/tests/test_waku_rpc.py
> +            jsonschema.validate(instance=response.json(), schema=json.load(schema))
I'd rather change that to be a 1-line method, something like
```suggestion
            self.validate_json_schema(instance=response, schema=method)
```

2024-08-19 15:31 UTC, glitchminer requested changes

2024-08-19 15:31 UTC, glitchminer commented on integration-tests/pytest.ini
> +    wakuext
missing accounts

2024-08-19 15:31 UTC, glitchminer commented on integration-tests/schemas/wakuext_peers
> +            ],
Are these ids static? Getting a intermittent fail on an id being required.

2024-08-19 15:56 UTC, antdanchenko commented on integration-tests/schemas/wakuext_peers
> +            ],
good catch, should be checking for a string of given length

2024-08-22 09:38 UTC, yevh-berdnyk approved these changes

2024-08-22 10:47 UTC, glitchminer approved these changes

2024-08-22 15:12 UTC, merged