chore(ci)_: adjust nightly tests build retention to 14 runs
status-im/status-go pull request #5746
Opened 2024-08-20 07:10 UTC by osmaczko

Increased build and artifact retention, as more context is usually needed when analyzing flakiness thorugh nightly tests.

2024-08-20 07:13 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4ea6cc75 | [#1](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5746/1/) | 2024-08-20 07:13:31 | ~2 min | `tests-rpc` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests-rpc/job/PR-5746/1//consoleText) |

2024-08-20 07:34 UTC, jakubgs requested changes

2024-08-20 07:34 UTC, jakubgs commented on _assets/ci/Jenkinsfile.tests
> +    )
We could make this simple:
```suggestion
    buildDiscarder(logRotator(
      numToKeepStr: '14',
      daysToKeepStr: '30',
      artifactNumToKeepStr: isTestNightlyJob() ? '14' : '1',
    ))
```

2024-08-20 07:57 UTC, osmaczko commented on _assets/ci/Jenkinsfile.tests
> +    )
True :+1: , applied.

2024-08-20 08:36 UTC, igor-sirotin approved these changes

2024-08-21 13:32 UTC, jakubgs approved these changes

2024-08-21 13:32 UTC, merged