fix_: chats and message history loading after login takes too much time
status-im/status-go pull request #5932
Opened 2024-10-10 01:08 UTC by qfrank

The status community has around 60 chats. Each chat costs `initChatFirstMessageTimestamp` around 120 ms in my ios simulator, so there is around an 8-second delay for `InitFilters`. The major cause is db io consumption. To reduce this, I combined all the chat parameters into one db query and made a simple cache for community queries. Also, I call save community only once for each community. Now the delay for `InitFilters` is reduced to around 800 ms. `initChatFirstMessageTimestamp` took around 251 ms

fix mobile [issue](https://github.com/status-im/status-mobile/issues/21358)

2024-10-10 01:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_multiplication_x: | a0de2a0a | [#1](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5932/1/) | 2024-10-10 01:11:40 | ~3 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5932/1//consoleText) |

2024-10-10 08:13 UTC, seanstrom commented on protocol/messenger.go
> +	var communityChats []*Chat
Maybe we could rename this function to: `initChatsFirstMessageTimestamp`

2024-10-10 10:43 UTC, seanstrom approved these changes
The changes look good, though I see there's some Codecov warnings for some of the new code. Is it possible to add some tests for functions that interact with the db?

2024-10-10 10:44 UTC, qfrank commented
> The changes look good, though I see there's some Codecov warnings for some of the new code. Is it possible to add some tests for functions that interact with the db?

Sure, I'll add it later thank you!

2024-10-10 15:53 UTC, jrainville requested changes
Very nice work. The speed up seems impressive.

I have some suggestions to make sure we reuse the code as best as possible and also to not publish without reason. The community description is the biggest offender in terms of using bandwidth so we need to be careful with publishing it.

2024-10-10 15:53 UTC, jrainville commented on protocol/messenger.go
> +	communityCache := make(map[string]*communities.Community)
We already have the same type of cache done above called `communityInfo`. Could we move this code to the main function to reuse the cache, or pass a ref to the cache, or even move the community cache to a `Messenger` prop?

I think passing a ref is probably the simplest and cleanest

2024-10-10 15:53 UTC, jrainville commented on protocol/messenger.go
> +		m.communitiesManager.Publish(&communities.Subscription{Community: community})
I don't think it makes sense to publish here, unless you actively checked if something changed. This way, we'll just be spamming the network on every all open.

Either you should check the community really changed and then publish, or just leave the publish to the normal sending loop.

If you go for the first option, you should also use `saveAndPublish` instead. It does the saving and the publishing while also checking that you are control node.

2024-10-11 02:33 UTC, qfrank commented on protocol/messenger.go
> +	communityCache := make(map[string]*communities.Community)
fixed

2024-10-11 02:33 UTC, qfrank commented on protocol/messenger.go
> +		m.communitiesManager.Publish(&communities.Subscription{Community: community})
fixed

2024-10-11 14:06 UTC, jrainville reviewed
Looks good I think the only thing left would be to use a pointer, otherwise the changes you make to the cache aren't actually shared with the original cache

2024-10-11 14:06 UTC, jrainville commented on protocol/messenger.go
> +func (m *Messenger) initChatsFirstMessageTimestamp(communityCache map[string]*communities.Community, chats []*Chat) {
```suggestion
func (m *Messenger) initChatsFirstMessageTimestamp(communityCache *map[string]*communities.Community, chats []*Chat) {
```
this way, you're passing the pointer/reference and you can change the original map and also it's lighter since it's not a new value

2024-10-11 14:24 UTC, qfrank commented on protocol/messenger.go
> +func (m *Messenger) initChatsFirstMessageTimestamp(communityCache map[string]*communities.Community, chats []*Chat) {
are you sure we need the extra pointer?
```go
type communityInfo struct {
	ID string
}

func TestPassMap(t *testing.T) {
	communityInfoMap := make(map[string]*communityInfo)
	communityInfoMap["1"] = &communityInfo{}
	updateCommunityInfo(communityInfoMap)
	require.Equal(t, "666", communityInfoMap["2"].ID)
}

func updateCommunityInfo(communityInfoMap map[string]*communityInfo) {
	communityInfoMap["2"] = &communityInfo{ID: "666"}
}
```

2024-10-11 14:27 UTC, jrainville approved these changes

2024-10-11 14:27 UTC, jrainville commented on protocol/messenger.go
> +func (m *Messenger) initChatsFirstMessageTimestamp(communityCache map[string]*communities.Community, chats []*Chat) {
Ah, since the `communityInfo` is a pointer, it still works! All good then

2024-10-15 03:58 UTC, ilmotta reviewed
Very nice work @qfrank!

2024-10-15 03:58 UTC, ilmotta commented on protocol/message_persistence.go
> +
A general recommendation:

> The error from rows.Err() could be the result of a variety of errors in the rows.Next() loop. The loop might exit for some reason other than finishing the loop normally, so you always need to check whether the loop terminated normally or not. An abnormal termination automatically calls rows.Close(), although it’s harmless to call it multiple times.
>
> -- http://go-database-sql.org/errors.html

Also here https://go.dev/doc/database/querying#multiple_rows_errors

```go
if err = rows.Err(); err != nil {
	return nil, err
}
```

2024-10-15 03:58 UTC, ilmotta commented on protocol/message_persistence.go
> +	args := make([]interface{}, len(chatIDs))
`[]interface{}` -> `[]any`

2024-10-15 03:58 UTC, ilmotta commented on protocol/message_persistence.go
> +				ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
I believe this is the first query in status-go using `partition by`. Not only for that, but I wonder if this query performs well when there are lots of rows in `user_messages`.

By any chance, did you run a query plan analysis on this query? One idea is to generate tons of rows (1k, 10k, 100k, and 1M) from a unit test and grab the test sqlite file to analyse.

2024-10-15 06:25 UTC, qfrank commented on protocol/message_persistence.go
> +				ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
Nice question, I used follow python script to generated 1M records into `user_messages`:
```python
import sqlite3
import random
import string
import time
from datetime import datetime, timedelta

# Connect to the database
conn = sqlite3.connect('your_database.db')
cursor = conn.cursor()

# Function to generate a random string
def random_string(length):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

# Function to generate a random date within the last year
def random_date():
    return int((datetime.now() - timedelta(days=random.randint(0, 365))).timestamp())

# Generate 1 million records
num_records = 1000000
batch_size = 1000

start_time = time.time()

for i in range(0, num_records, batch_size):
    values = []
    for j in range(batch_size):
        if i + j >= num_records:
            break
        
        values.append((
            random_string(32),  # id
            random.randint(1600000000, int(time.time())),  # whisper_timestamp
            random_string(10),  # source
            random_string(100),  # text
            random.randint(0, 5),  # content_type
            random_string(15),  # username
            random_date(),  # timestamp
            random_string(32),  # chat_id
            random_string(32),  # local_chat_id
            random.choice([0, 1]),  # hide
            random_string(32) if random.random() < 0.1 else None,  # response_to
            random.randint(0, 5),  # message_type
            random.randint(1, 1000000),  # clock_value
            random.choice([0, 1]),  # seen
            random.choice(['sent', 'delivered', 'read']),  # outgoing_status
            random_string(50).encode(),  # parsed_text
            random.choice([0, 1]),  # rtl
            random.randint(1, 10),  # line_count
            random.choice([0, 1]),  # mentioned
            random_date() if random.random() < 0.1 else None,  # edited_at
            random.choice([0, 1]),  # deleted
            random.randint(0, 3),  # contact_request_state
            random_string(20) if random.random() < 0.1 else "",  # discord_message_id
            random.choice([0, 1]),  # deleted_for_me
            random.randint(0, 2),  # contact_verification_status
            random_string(32) if random.random() < 0.1 else None,  # album_id
            random.choice([0, 1]),  # replied
            random.randint(100, 1000) if random.random() < 0.2 else None,  # image_width
            random.randint(100, 1000) if random.random() < 0.2 else None,  # image_height
            random_string(32) if random.random() < 0.05 else None,  # deleted_by
            random.randint(1, 10) if random.random() < 0.1 else 0,  # album_images_count
        ))

    cursor.executemany('''
    INSERT INTO user_messages (
        id, whisper_timestamp, source, text, content_type, username, timestamp, chat_id, local_chat_id,
        hide, response_to, message_type, clock_value, seen, outgoing_status, parsed_text, rtl, line_count,
        mentioned, edited_at, deleted, contact_request_state, discord_message_id, deleted_for_me,
        contact_verification_status, album_id, replied, image_width, image_height, deleted_by, album_images_count
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', values)

    if (i + batch_size) % 100000 == 0:
        conn.commit()
        print(f"Inserted {i + batch_size} records")

conn.commit()
cursor.close()
conn.close()

end_time = time.time()
print(f"Inserted {num_records} records in {end_time - start_time:.2f} seconds")
```

Then tried following the query and it ended in 211 ms. looks good? 🤔

```sql
SELECT
    m1.local_chat_id,
    m1.whisper_timestamp
FROM (
         SELECT
             m1.local_chat_id,
             m1.whisper_timestamp,
             ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
         FROM user_messages m1
         WHERE m1.local_chat_id IN (
                                    'ngO4zPugiB3FEl89SWVRx6Iz36Z62J3q',
                                    'zpgd5Dx7exAuBnynngvmQmw8ljD8a90T',
                                    'UkFHdjB537zBT0Aloxsiqy98EC7Uyjfp',
                                    'GuRwYMcswAns8fJ11BtXahvBEg5ctoaT',
                                    '3jOElCI2uZCObP6xKWGBikrh0ZyXlZow',
                                    'aqwiwJIpJzPp7k7IkDNSAvFGnIWkRUZy',
                                    'ob3zKgnxWj5gH4whPvM6u9PUBWLG48Ai',
                                    'VR0yUJuxAXNoTegg8mAkBIMPe4ZuaF0c',
                                    'QhGx83VdQlfKA7ViWdG8pUBwZYO93Ztr',
                                    'aUIJP1eL58jqwP0J3z2h5njXJxETf3gA',
                                    '3gO0YB89LLCWXsVQHvXZHCgopZiTdKmX',
                                    '3ukti2ncPqyNHhIFX62Y2ztakrLIC9hL',
                                    'vw3pvJj1uuh1pjrYUGnBCvuxHh5vcKai',
                                    'pcij9DK3CQxjxIsRvnSezSJBSs5xNyta',
                                    '8AdaW0NRSXkzicqQee321HpQA6OyeMRL',
                                    'oqC7UEokLZSLQ8B9WuBQkQF6PCMimeTM',
                                    '2ovRmn0vIgHxvXh2bsKtOmRycK38Ck3N',
                                    'FwjwQyDLtqNcGRlCcZHbVCegqDcCL0Y3',
                                    'kvTDvfYL0ouusLooQ05ImjU27z0Qo2nd',
                                    'aNVAiZMfJ8LIGzQfRGbxK8oIRdL0f7IM',
                                    'sjX0d6moeuV7fQzUGpUAuA0Sk4lZVzji',
                                    '9ncyXL6COmw2vAf5mDzarfljou6D0wiX',
                                    'VPIuSTj8HJE0r5sZyvtPS5WxLvuF2g57',
                                    'L8XXRA9eneGIAZ8TGwCclsiFZNpyJMNw',
                                    'aXUbyxmrKp8WWidlskyKagbhlAYqCKh0',
                                    'cUXJDEgEg06BJkB2azlZuOYmdRQuFsnu',
                                    'buW1mGc3eH37gzsvJbov16zzluJjdn9M',
                                    'I7SYYWEXXaCk3JwnSYoJejCt4Vrn5WNX',
                                    'Vek9vID9knpErwMoaDRd0B3yV3AADzA1',
                                    'pd0kK8Vgjbf3GI2WdGvYwDNIICLaI4XF',
                                    'TM2m18xF212BgJNzhhZwTg1EOgoWBoy4',
                                    '9jrhtPOoZlHUrU9czXeAp2W8JZ06pI1y',
                                    'M2EOMuTb5zfQUrP09RJOiAOXedmnpzua',
                                    'kW7DqCDILHhIIgu9JrHFQO3rU8CJBFZS',
                                    'j6wLUdEb27NCDFp5OseKhM3URuXC5L7o',
                                    '6ixotqEF0slrIfFA3NPVVcTFV4L8zxg2',
                                    'NmtzmH6NtqisjSbcq9Etp9QgOW5TsaK3',
                                    '8k91kKj7deIQOWkxsFYXAmbf66UXwVIQ',
                                    'NLuDjJM7jNzSeErOzWHSdR2afx0AV65Z',
                                    'Vb7RZBvRhyVnJsJTj6RUYy3PJj0QOI69',
                                    '8tZdXC2N0akgmfrJ3ggsXzY0nUgJXz5z',
                                    'ItrAZq6eCDbgO7Ud58RVcoObIf78bIGe',
                                    'ZnUS7SFdQ3xp5BfKzEZz5VhyYELmB4yf',
                                    'iwQrgOuevZi5c3nUKhNMbyQAynlNd7pU',
                                    'QrJbHIiNqzNstmgGlzX1BjDE9hLBItvC',
                                    'G1qk0OgEMdd9hTDS8gzOvc6Htwf3Dc1Y',
                                    'zQewDmdfFfeQYHPjImcFVdtBMzpTMxJc',
                                    'D0oeKfyEL4ZFoYhRT7Lqj5EGYGku2Mtv',
                                    '3i1pGIRo48FxhKHq0Hs5t67opCPJTCxV',
                                    'syy2MT6mdAKLkUQbApvSCR4hjKdX8NiV',
                                    'CYHJdWTcFZrCMXA54SyQhjNrMP92XWjl',
                                    '7nasHxbDZh1vYYubsm0ijKQ8fSgra3nG',
                                    'TwyhsaJiPkKzW3QwZWq1DIf4Y6GLiOSR',
                                    '3ehJUDUBtvJc3gzXE2R8hNj6DQzDgnkA',
                                    '7dVA7kT3v69R6A6 [...]

2024-10-15 06:28 UTC, qfrank commented on protocol/message_persistence.go
> +	args := make([]interface{}, len(chatIDs))
I need tell AI to use `any` over `interface{}` 😅

<img width="447" alt="image" src="https://github.com/user-attachments/assets/8faf8be3-1510-4656-8d41-c539797a942d">

emm.. the rules looks good 😊

<img width="644" alt="image" src="https://github.com/user-attachments/assets/ade51547-8d0b-421e-907b-16deb360a75f">

2024-10-15 06:53 UTC, qfrank commented on protocol/message_persistence.go
> +
fixed

2024-10-15 06:54 UTC, qfrank commented on protocol/message_persistence.go
> +	args := make([]interface{}, len(chatIDs))
fixed

2024-10-15 17:45 UTC, ilmotta commented on protocol/message_persistence.go
> +				ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
Lovely script ;) Seems pretty fast, although it's also running in your powerful dev machine.

> we had the index(idx_search_by_local_chat_id_sort_on_cursor) already, so I think the performance should be ok.

If you didn't see anything suspicious in the output of the query plan then it's great!

2024-10-15 17:46 UTC, ilmotta commented on protocol/message_persistence.go
> +	args := make([]interface{}, len(chatIDs))
Yep 😆 chatgpt refuses to use the alias without guidance.

2024-10-15 17:47 UTC, ilmotta approved these changes

2024-10-16 09:15 UTC, qfrank commented on protocol/message_persistence.go
> +				ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
There did exist suspicion in the output of the query plan! Previous result looks good because I ignored generating massive records which contain the same local_chat_id! If I add another 1M record with the same local_chat_id, sql execution will take > 20s , after trying different sqls, I think I find the best sql:
```sql
SELECT
    m1.local_chat_id,
    m1.whisper_timestamp,
    min(substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id)
FROM user_messages m1
WHERE m1.local_chat_id IN (
                           'ngO4zPugiB3FEl89SWVRx6Iz36Z62J3q',
                           ...
    )
group by m1.local_chat_id
```

it will take around 1s, and the query plan will be pretty simple now 👍
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/3adf4272-d768-44e2-a97e-4dc55328adc5">

But I doubt if it will be enough for real user as time fly

2024-10-18 02:25 UTC, merged

2024-10-23 04:45 UTC, ilmotta commented on protocol/message_persistence.go
> +				ROW_NUMBER() OVER (PARTITION BY m1.local_chat_id ORDER BY substr('0000000000000000000000000000000000000000000000000000000000000000' || m1.clock_value, -64, 64) || m1.id ASC) AS rn
Query plan looks straightforward indeed. Nice!