Make notification pluggable
status-im/status-go pull request #595
Opened 2018-01-31 16:13 UTC by denismakogon

This PR is about to introduce full freedom for notification mechanism.

Making notification really pluggable
    
     What's new?
        - abstracting from fcm client
        - notification backend defined at geth/api geth/backend layer
        - refactoring of all notification stuff (was in geth/common and get/notification, now at geth/notification only)
        - corresponding changes to geth/api.go and geth/backend.go to reflect pluggability for notifications
    
Note: This PR based on fixes for tests from PR #593
    
Closes: #499

2018-01-31 16:14 UTC, denismakogon commented
Would be nice if someone can help with resolving notification issues, a bit new to `geth` testing framework.

2018-01-31 22:59 UTC, divan commented
Hey, thanks for the PR. I'm not aware of any other notification method though. @oskarth do you have anything in mind? Are we going to use Firebase for now?

Understanding what other notification implementations we are going/planning to support (if any) is important to do a proper generalization. For example, currently `notification.Client` interface has method `NewRegIdsMsg()` which seems to be just a copy-paste of the Firebase client naming (I have no idea what it does by looking at the name, btw). And it's possible that another notification mechanism will work differently and thus abstraction/generalization should be different.

2018-02-01 13:22 UTC, oskarth commented
We definitely want to be able to support more notifications providers. But it is also a good point that it is hard to do abstraction without having at least two (ideally three) ways of using it.

I don't personally have any specific provider in mind. I would have to think more carefully about this to know what a good abstraction might look like. Can you think of any other providers in particular @denismakogon? To make sure we get the design right.

2018-02-01 13:49 UTC, denismakogon commented
I agree that initial code a bit rough, i'm working towards changing that with respect to possible alternatives. So answering @oskarth question, there are few alternatives to firebase, but here's what i have for you:
1. [Back4App](https://www.back4app.com/product/parse-server-push-notifications)
2. [CloudBoost.io](https://cloudboost.io/)

2018-02-01 14:42 UTC, denismakogon commented
I'm not sure how can I overcome `codeclimate` check because it complains to auto-generated file, so leaving this as is.

One question, taking into account other push message services (alternatives to Firebase) there would be a need to slightly update the payload structure because almost all of them expect title and message, any other stuff that this PR introduces is nothing really necessary (except Firebase, of course).

2018-02-19 14:51 UTC, mandrigin requested changes
Looks good!
A few minor questions.

2018-02-19 14:51 UTC, mandrigin commented on geth/notification/notification.go
> +func NewNotification(client Client) Constructor {
That isn't a notification, right? That is a factory or a constructor.

2018-02-19 14:51 UTC, mandrigin commented on geth/notification/payload.go
> +func (p *Payload) ToFCMNotificationPayload() *fcm.NotificationPayload {
Maybe FirebaseClient (1) should know how to handle `notification.Payload` (2) instead of making (2) aware of (1)?

2018-02-19 14:51 UTC, mandrigin commented on geth/notification/response.go
> +func FromFCMResponseStatus(f *fcm.FcmResponseStatus) *Response {
I think that `FirebaseClient` should be responsible for constructing a  correct response.

2018-03-26 13:10 UTC, dshulyak commented
Closing this as a PR definitely in limbo and codebase somewhat changed

2018-03-26 13:10 UTC, closed without merging