test_: Code Migration from status-cli-tests
status-im/status-go pull request #5990
Opened 2024-10-24 14:39 UTC by shashankshampi

Changes:

- Added contract request
- Migrated contract request test from the old repository https://github.com/status-im/status-cli-tests
- Added validation with signal
- Added response validation
- Helper and methods to support migration

2024-10-24 14:41 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_multiplication_x: | 1966f501 | [#1](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5990/1/) | 2024-10-24 14:41:10 | ~1 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5990/1//consoleText) |

2024-10-28 08:29 UTC, fbarbu15 commented on tests-functional/src/node/status_node.py
> +        command = ["./status-backend", f"--address=localhost:{self.port}"]
I get `FileNotFoundError: [Errno 2] No such file or directory: './status-backend'`
There is not such folder
Did you copied anything? How can I run this on my local machine?

2024-10-28 10:52 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        timestamp, message_id = self.send_with_timestamp(
why would we send 2 contact requests (line 90 and line 95)?
if you need the whole response then you don't need to use `send_with_timestamp` and you can make your own processing(of response, message_id and timestamp)

2024-10-28 10:52 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
I would expect that we check in the signals a sign that the  contact request was received. 
Are those lines relevant to our test?

2024-10-28 10:52 UTC, fbarbu15 commented on tests-functional/validators/contact_request_validator.py
> +        print("All validations passed for the contact request response.")
We use logger not print

2024-10-28 10:52 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        assert self.second_node.wait_for_logs([message])
wait_for_logs doesn't exist

2024-10-30 05:10 UTC, shashankshampi commented on tests-functional/src/node/status_node.py
> +        command = ["./status-backend", f"--address=localhost:{self.port}"]
Need status-backend binary in root.
I have updated README now.

2024-10-30 05:12 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
I have added a logger to print the received signal.
Validating the signal value along with just the signal event name will make the test stronger.

2024-10-30 05:13 UTC, shashankshampi commented on tests-functional/validators/contact_request_validator.py
> +        print("All validations passed for the contact request response.")
Fixed it with logger.

2024-10-30 05:26 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        assert self.second_node.wait_for_logs([message])
fixed now

2024-10-30 05:29 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        timestamp, message_id = self.send_with_timestamp(
We are not sending 2 request

Node 2 --> Node 1

I have removed comment for confusion  
Its good to send with now  timestamp

2024-10-30 06:33 UTC, shashankshampi reviewed
Addressed review comments

2024-10-30 10:15 UTC, fbarbu15 requested changes

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/README.MD
> +Here’s the updated README with the additional prerequisites and instructions:
Again you are using AI Companion without checking it's output ...

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/README.MD
> +   pre-commit install
where is the pre-commit config that you install? I don't see it
you also don't install the `pre-commit` lib

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/README.MD
> +Location of the binary: `cmd/status-backend/status-backend`
you don't mention that the binary needs to be added in the root
I think we should add a script that gets executed in the test setup (a fixture) that will check if the binary exists and if not will try to copy it. If that fails it will raise an Exception saying that we can't run the tests without the binary

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/README.MD
> +This README should cover your additional setup, installation, and testing instructions with clear steps for users. Let me know if there are any further modifications needed!
please self-review your own code so things like this are caught by you...

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
why declare the logger here?
this breaks consistency (see how you declare it in `tests-functional/src/libs/base_api_client.py` ) and also leads to duplication as you add the same line to each function

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/clients/signals.py
> +        logger.info(f"Received signal: {signal_data}")
this is too verbose, makes console output huge
please log it to a file

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/libs/base_api_client.py
> +from tenacity import retry, stop_after_delay, wait_fixed
tenacity is not in `requirements.txt`, how did this work for you?

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/libs/common.py
> +import allure
allure also not installed

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/libs/common.py
> +def attach_allure_file(file):
where are you using this?

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/libs/common.py
> +    """Generate a unique data directory for each node instance."""
inconsistencies again, probably created by the use of AI Companion
- you are using type hints here while in other places (code copied from status_cli) you don't
- you added docstrings while other functions use logging

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/node/status_node.py
> +        """Start the node using a subprocess command."""
such comments are not needed IMO since we also have logs that say the same thing

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/node/status_node.py
> +        self.log_thread = self.capture_process_logs(self.process, self.logs)
why do we capture process logs since we have signals?

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/node/status_node.py
> +        self.log_thread = self.capture_process_logs(self.process, self.logs)
we may need this, but just wondering what is the use case

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/src/steps/common.py
> +    def start_1_node(self):
where are you using this?

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        timestamp, message_id = self.send_with_timestamp(
Please read the code, You are sending 2 `send_contact_request`, one here, by using `send_with_timestamp` function

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        response = second_node.send_contact_request(first_node_pubkey, contact_request_message)
and one here by using `send_contact_request` directly

2024-10-30 10:15 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
Those events are meaningless, for this test. You should check an event that the contact request was received. I can see such signals in `first_node` that are way more relevant to this test:
```
{
    "event": {
        "activityCenterNotifications": [
            {
                "accepted": false,
                "albumMessages": null,
                "author": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                "chatId": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                "communityId": "",
                "contactVerificationStatus": 0,
                "deleted": false,
                "dismissed": false,
                "id": "0xa60142d29e7e62165208a72986379a993039901353b9e19706989fcb80c47291",
                "installationId": "",
                "lastMessage": null,
                "membershipStatus": 0,
                "message": {
                    "alias": "zQ3...YavoYu",
                    "chatId": "0x04f3259c201c6bd7dc9e77a5d1a5a5212d4bbd90a28aadcfb641016f11856ce8138c34ffc0d7f218db24e0ec09e8fe361a891278cc3480876ab204d5997efbc81a",
                    "clock": 1730276830518,
                    "compressedKey": "zQ3shjsb6PpL2qx7twUmo1EiX5rLjcj6BkuyE2QTSzrYavoYu",
                    "contactRequestState": 1,
                    "contentType": 11,
                    "displayName": "test_user_second_0",
                    "emojiHash": [
                        "🪖",
                        "🙍🏼",
                        "👱🏼",
                        "🆓",
                        "🤼‍♀️",
                        "🥝",
                        "🥑",
                        "👩‍🦼",
                        "🚯",
                        "🧝🏾‍♀️",
                        "🙉",
                        "👨🏼‍🦼",
                        "😣",
                        "👩‍🦰"
                    ],
                    "ensName": "",
                    "from": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                    "id": "0xa60142d29e7e62165208a72986379a993039901353b9e19706989fcb80c47291",
                    "identicon": "",
                    "lineCount": 0,
                    "localChatId": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                    "messageType": 1,
                    "new": true,
                    "parsedText": [
                        {
                            "children": [
                                {
                                    "literal": "contact_request_0"
                                }
                            ],
                            "type": "paragraph"
                        }
                    ],
                    "quotedMessage": null,
                    "replace": "",
                    "responseTo": "",
                    "rtl": false,
                    "seen": false,
                    "text": "contact_request_0",
                    "timestamp": 1730276830518,
                    "whisperTimestamp": 1730276831000
                },
                "name": "test_user_second_0",
                "read": false,
                "replyMessage": null,
                "timestamp": 1730276831000,
                "tokenData": null,
                "type": 5,
                "updatedAt": 1730276834467
            }
        ],
        "activityCenterState": {
            "hasSeen": false,
            "updatedAt": 1730276834467
        },
        "chats": [
            {
                "active": false,
                "alias": "zQ3...YavoYu",
                "chatType": 1,
                "color": "",
                "deletedAtClockValue": 0,
                "description": "",
                "emoji": "",
                "highlight": true,
                "id": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                "identicon": "",
                "joined": 1730276834465,
                "lastClockValue": 1730276830530,
                "lastMessage": {
                    "alias": "zQ3...YavoYu",
                    "chatId": "0x04f3259c201c6bd7dc9e77a5d1a5a5212d4bbd90a28aadcfb641016f11856ce8138c34ffc0d7f218db24e0ec09e8fe361a891278cc3480876ab204d5997efbc81a",
                    "clock": 1730276830530,
                    "compressedKey": "zQ3shjsb6PpL2qx7twUmo1EiX5rLjcj6BkuyE2QTSzrYavoYu",
                    "contactRequestState": 1,
                    "contentType": 11,
                    "displayName": "test_user_second_0",
                    "emojiHash": [
                        "🪖",
                        "🙍🏼",
                        "👱🏼",
                        "🆓",
                        "🤼‍♀️",
                        "🥝",
                        "🥑",
                        "👩‍🦼",
                        "🚯",
                        "🧝🏾‍♀️",
                        "🙉",
                        "👨🏼‍🦼",
                        "😣",
                        "👩‍🦰"
                    ],
                    "ensName": "",
                    "from": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                    "id": "0xb096dc1061930bcc3a35a5b7db4cf9106ab2a2907b752359a7beaafe9d860caa",
                    "identicon": "",
                    "lineCount": 0,
                    "localChatId": "0x044dbe9b62779035d6521028a1a8e4bff5921c7ac4565262716b3b246ad559952af089f68cb5ae46de39a5fb1f3d4c6de039ccbef0917725e772db975db30766d9",
                    "messageType": 1,
                    "new": true,
                    "parsedText": [
                        {
                            "children": [
                                {
                                    "literal": "contact_request_0"
                                }
                            ],
                            "type": "paragraph"
                        }
                    ],
                    "quotedMessage": null,
                    "replace": "",
                    "responseTo": "",
                    "rtl": false,
                    "seen": false,
                    "text": "contact_request_0",
                    "timestamp": 1730276830530,
                    "whisperTimestamp": 1730276831000
                },
                "members": null,
                "membershipUpdateEvents": null,
                "muted": false,
                "muteTill": "0001-01-01T00:00:00Z",
                "name": "0x044dbe",
                "ReadMessagesAtClockValue": 0,
                "timestamp": 1730276834468,
                "unviewedMentionsCount": 2,
                "unviewedMessagesCount": 2,
                "viewersCanPostReactions": false
            }
        ],
        "contacts": [
            {
                "active": false,
                "added": false,
                "address": "0xea24daf757489c25c1af4f9afd223368f134d4e6",
                "alias": "zQ3...YavoYu",
                "bio": "",
                "blocked": false,
                "compressedKey": "zQ3shjsb6PpL2qx7twUmo1EiX5rLjcj6BkuyE2QTSzrYavoYu",
                "contactRequestLocalClock": 0,
                "contactRequestLocalState": 0,
                "contactRequestRemoteClock": 1730276830530,
                "contactRequestRemoteState": 3,
                "contactRequestState": 3,
                "customizationColor": "primary",
                "displayName": "test_user_second_0",
                "emojiHash": [
                    "🪖",
                    "🙍🏼",
                    "👱🏼",
                    "🆓",
                    "🤼‍♀️",
      [...]

2024-10-30 15:27 UTC, shashankshampi reviewed
Thanks for review.
Have addressed all points.

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/README.MD
> +Here’s the updated README with the additional prerequisites and instructions:
sorry.
Fixed

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/README.MD
> +This README should cover your additional setup, installation, and testing instructions with clear steps for users. Let me know if there are any further modifications needed!
fixed

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/node/status_node.py
> +        """Start the node using a subprocess command."""
removed unwanted comments.
Thanks

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/node/status_node.py
> +        self.log_thread = self.capture_process_logs(self.process, self.logs)
I used this log to see the API calls and flow.
 Function returns the log_thread instance, allowing the calling function to interact with the thread if needed

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/steps/common.py
> +    def start_1_node(self):
Removed it for now as when require in next test will add it.

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        timestamp, message_id = self.send_with_timestamp(
My bad. got it.
fixed it now

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        response = second_node.send_contact_request(first_node_pubkey, contact_request_message)
My bad. got it.
fixed it now

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
sure. Have removed the event details validation.

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/libs/common.py
> +    """Generate a unique data directory for each node instance."""
removed it.
Thanks

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/libs/common.py
> +def attach_allure_file(file):
no plan to use in near feature 
Have removed it .

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/libs/common.py
> +import allure
removed it as not required

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
fixed.
Thanks

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/README.MD
> +   pre-commit install
cleaned up now

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/README.MD
> +Location of the binary: `cmd/status-backend/status-backend`
Thanks for the suggestion.
Added check which ensures if the binary is missing its package and placed in the right path and if it already exists, it doesn't build [just to save time locally in multiple executions]

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/clients/signals.py
> +        logger.info(f"Received signal: {signal_data}")
Now added logic to write in file in /reports

2024-10-30 15:27 UTC, shashankshampi commented on tests-functional/src/node/status_node.py
> +        command = ["./status-backend", f"--address=localhost:{self.port}"]
Added logic to build and place binary in right place. No manual work anymore

2024-10-30 15:29 UTC, shashankshampi commented on tests-functional/src/libs/base_api_client.py
> +from tenacity import retry, stop_after_delay, wait_fixed
updated requirement.

2024-10-30 15:37 UTC, status-im-auto commented
#### :heavy_check_mark: [status-go/prs/macos/x86_64/main/PR-5990#11](https://ci.status.im/job/status-go/job/prs/job/macos/job/x86_64/job/main/job/PR-5990/11/) :small_blue_diamond: ~10 min :small_blue_diamond: 5b374662 :small_blue_diamond: [:package: macos package](https://status-im-prs.ams3.digitaloceanspaces.com/status-go-macos-241030-152723-5b3746-pr5990.zip)

2024-10-31 12:38 UTC, fbarbu15 commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
You only fixed this line!
But you are using `logger = logging.getLogger(__name__)` for other lines as well...
Did you checked how you are using logger in the other file  `tests-functional/src/libs/base_api_client.py`?

```
from src.libs.custom_logger import get_custom_logger
logger = get_custom_logger(__name__)
```

Please apply review suggestions in all places

2024-10-31 12:53 UTC, fbarbu15 requested changes
Please response to the comment about signals, I don't think you understood what we need to test here

2024-10-31 12:53 UTC, fbarbu15 commented on tests-functional/requirements.txt
> +websocket_client==1.4.2
the lib is `websocket-client`

why did you changes existing requirements?

2024-10-31 12:53 UTC, fbarbu15 commented on tests-functional/src/libs/common.py
> +SOURCE_DIR = GO_PROJECT_ROOT / "cmd/status-backend"
how did this work for you? 
this should be 

`SOURCE_DIR = GO_PROJECT_ROOT / "build/bin"`

2024-10-31 12:53 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
@shashankshampi  have you understood how this test should work? 
Why do we care about signals and what do we need to check inside the signals?

This is outdated. Already removed signal value validation. @fbarbu15 
More context on this here: https://github.com/status-im/status-go/pull/5990#discussion_r1822290921

2024-10-31 15:49 UTC, shashankshampi reviewed
Addressed all comments.
Thanks

2024-10-31 15:49 UTC, shashankshampi commented on tests-functional/requirements.txt
> +websocket_client==1.4.2
I used `pipreqs` to generate requirements.
Not sure if that makes any difference but have restored it now to the original

2024-10-31 15:49 UTC, shashankshampi commented on tests-functional/src/libs/common.py
> +SOURCE_DIR = GO_PROJECT_ROOT / "cmd/status-backend"
I am on latest develop branch and I can see this binary is generated on this path only and works fine on MacOS under all scenarios
 
- existing binary
- fresh binary build and copied

<img width="345" alt="image" src="https://github.com/user-attachments/assets/a922f10d-4799-4928-951a-63c1fdfbad9d">

Are you seeing different build paths on Windows?

2024-10-31 15:49 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
If you look over signals generated in files/reports you will observe that signals have similar JSON structures like API response.
Now in this repo people are just validating event name of the signal but you can actually validate each things with response, request with signal data. 
The scope of the test is limited to the network. So, I removed signal body validation and only checked if specific signal was being triggered on action [API request].

This is how a JOSN signal formate looks like 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/2829824e-2608-45bf-aa34-5e0ad50ed83b">

But I still feels if someone is actually validating RPC request must do response --> request , response --> signal event validation.

We can discuss or call if more clarification is required or if I am missing anything on this.

2024-10-31 15:49 UTC, shashankshampi commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
I missed other places.
thanks have fixed it now.

2024-10-31 16:25 UTC, fbarbu15 commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
No, we need to verify that the signal that corresponds with the contact request is received in the peer node. 
So when you send a contact request from node1 to node2 you need to verify in the node2 that you received a signal that corresponds to that contact request. I already sent you the exact signal that needs checking. I don't know what else to say.

2024-10-31 16:27 UTC, fbarbu15 commented on tests-functional/src/libs/common.py
> +SOURCE_DIR = GO_PROJECT_ROOT / "cmd/status-backend"
yes, on WSL (Ubuntu) is on "build/bin", strange

2024-10-31 16:31 UTC, fbarbu15 requested changes
we need to validate that the receive signal is correct

2024-10-31 16:36 UTC, fbarbu15 commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
no, you haven't...
you still use 

`logger = logging.getLogger(__name__)` instead of how I suggested

2024-11-02 13:54 UTC, shashankshampi commented on tests-functional/tests/test_contact_request.py
> +        expected_event_started = {"requestId": "", "peerId": "", "batchIndex": 0, "numBatches": 1}
Added validation of event with requested and response data

2024-11-02 14:39 UTC, shashankshampi commented on tests-functional/clients/signals.py
> +        logger = logging.getLogger(__name__)
it was existing code. There are other existing code where lib logging is used. I have changed in Signal as I have modified this file.

2024-11-07 08:38 UTC, fbarbu15 reviewed
Tried this locally and works fine on my machine.
Left one comment
@shashankshampi  could you please ask Anton for review?

2024-11-07 08:38 UTC, fbarbu15 commented on tests-functional/validators/contact_request_validator.py
> +class ContactRequestValidator:
this validator looks very similar to the MessageValidator, I think we can merge them and add a condition for any diffs

2024-11-12 08:19 UTC, fbarbu15 commented
Closing as work will be continued here https://github.com/status-im/status-go/pull/6063

2024-11-12 08:19 UTC, closed without merging