fix(ci)_: skip windows build cleanup stage
status-im/status-go pull request #6003
Opened 2024-10-28 20:06 UTC by mendelskiv93

Windows build pipeline has errors while running:
```sh
sh "rm -rf ${env.WORKSPACE}@tmp"
```
in cleanup stage.
```groovy
19:11:41  process apparently never started in J:/Users/jenkins/workspace/_prs_windows_x86_64_main_PR-5990@tmp/durable-478fb71e
19:11:41  (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
```
might be related with [Durable Task Plugin](https://plugins.jenkins.io/durable-task/). 

Quick fix would be skipping this stage on Windows due to `tmp` folder being empty, as they should be at the end of the pipeline. 
Opting only for
```groovy
cleanup { cleanWs() }
```
as post cleanup step.

2024-10-28 20:12 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 25020e0f | [#1](https://ci.status.im/job/status-go/job/prs/job/linux/job/x86_64/job/main/job/PR-6003/1/) | 2024-10-28 20:12:02 | ~5 min | `linux` | [:package:`zip`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/status-go-linux-241028-200631-25020e-pr6003.zip) |

2024-10-28 22:38 UTC, jakubgs requested changes
Did you actually trying using `LAUNCH_DIAGNOSTICS=true` as the error suggests?

2024-10-28 22:38 UTC, jakubgs commented on _assets/ci/Jenkinsfile.desktop
>      stage('Cleanup') {
Wait, why is this in some kind of special `Cleanup` stage when there's a dedicated `post { cleanip {} }` stage?

2024-10-29 11:42 UTC, jakubgs approved these changes

2024-10-29 11:47 UTC, jakubgs commented
It appears the Durable Task plugin cannot be installed because it is required by Docker plugin:

![image](https://github.com/user-attachments/assets/40fdd9cf-7bfc-4179-bd68-a5097da79929)

2024-10-30 08:53 UTC, markoburcul approved these changes

2024-10-30 11:38 UTC, merged