test_: Code Migration from status-cli-tests for 1 on 1 message
status-im/status-go pull request #6022
Opened 2024-10-31 15:52 UTC by shashankshampi

Changes:

Added 1 on 1 message Test 

Migrated contract request test from the old repository https://github.com/status-im/status-cli-tests
Added validation with signal
Added response validation
Helper and methods to support migration

2024-10-31 15:55 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_multiplication_x: | b1222d70 | [#1](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-6022/1/) | 2024-10-31 15:55:07 | ~2 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-6022/1//consoleText) |

2024-10-31 16:30 UTC, fbarbu15 requested changes

2024-10-31 16:30 UTC, fbarbu15 commented on tests-functional/tests/test_one_to_one_messages.py
> +                receiving_node.wait_for_signal("messages.new", None)
same as with the old PR, we need to check that the message_text or message_id that we send in the sending_node is present in the signal

2024-10-31 16:30 UTC, fbarbu15 commented on tests-functional/validators/message_validator.py
> +logger = logging.getLogger(__name__)
again not using the custom logger

2024-11-03 10:54 UTC, shashankshampi reviewed
Addressed all PR review.
Merging into main PR

2024-11-03 10:54 UTC, shashankshampi commented on tests-functional/tests/test_one_to_one_messages.py
> +                receiving_node.wait_for_signal("messages.new", None)
added validation for text, name and id

2024-11-03 10:54 UTC, shashankshampi commented on tests-functional/validators/message_validator.py
> +logger = logging.getLogger(__name__)
updated to custom logger

2024-11-03 10:56 UTC, merged