[WIP] update mainnet dev cluster config
status-im/status-go pull request #745
Opened 2018-03-20 14:50 UTC by adambabik

The nodes in mainnet dev cluster changed a bit.

2018-03-20 15:10 UTC, themue requested changes
Renaming of field needed. What is the motivation behind the new order and why especially this one:

- 163... and 51... port 30303
- 163... and 51... port 30503
- 163... and 51... port 30403

Maybe my eyes don't catch the real sorting. 😁

2018-03-20 15:10 UTC, themue commented on static/config/cluster.json
> +      "bootnodes": []
`"bootnodes"` are `"staticnodes"` now.

2018-03-22 09:10 UTC, adambabik commented
@themue I fixed that. Sorted by IP and then by port.

2018-03-22 10:02 UTC, themue approved these changes
LGTM

2018-03-22 14:58 UTC, merged