Use status-im/go-web3js
status-im/status-go pull request #764
Opened 2018-03-26 11:56 UTC by dshulyak

2018-03-28 08:27 UTC, mandrigin requested changes
Looks good, a tiny little comment would be nice to have.

2018-03-28 08:27 UTC, mandrigin commented on Gopkg.lock
> +  name = "github.com/status-im/go-web3js"
Can you add a short description of this dependency right into this file?
Maybe with even a link to README (looks like overkill, but it makes it more convenient when one needs to regenerate and update dependency).

2018-04-04 11:12 UTC, dshulyak commented
@mandrigin added a comment to Gopkg.toml

2018-04-04 11:23 UTC, mandrigin approved these changes

2018-04-04 11:23 UTC, mandrigin commented
Looks good now!

2018-04-09 13:34 UTC, adriacidre approved these changes

2018-04-09 13:36 UTC, themue approved these changes
Nice one. 👌

2018-04-09 13:42 UTC, merged

2018-04-09 13:56 UTC, dshulyak commented
anyone noticed if this change passed ci? :)

2018-04-09 14:23 UTC, mandrigin commented
@dshulyak nope, but what is the point of the CI if it doesn't block merging?..