[#732] Create status-go API to return a current revision
status-im/status-go pull request #804
Opened 2018-04-06 09:45 UTC by ovx

A new API endpoint `StatusGoVersion`. Returns current build version.

- added a new API endpoint
- endpoint exported for xgo

Closes #732

2018-04-06 10:01 UTC, adambabik requested changes

2018-04-06 10:01 UTC, adambabik commented on geth/api/api.go
> +func (api *StatusAPI) StatusGoVersion() string {
I think it can be named `Version()`. There are no other components than `StatusGo`.

2018-04-06 10:01 UTC, adambabik commented on lib/library.go
> +func StatusGoVersion() *C.char {
This also can be named `Version`.

2018-04-06 10:01 UTC, adambabik commented on t/e2e/api/api_test.go
> +	var (
`var` is not needed, `require := s.Require()` will work just fine.

Also, I don't think you need to start the node here. 

```go
version := s.api.StatusGoVersion()
s.Equal(params.Version, version)
```

should be enough.

2018-04-06 18:21 UTC, dshulyak commented
are we certain that we need a binding for that and not rpc call `status_version` such as https://github.com/ethereum/wiki/wiki/JSON-RPC#web3_clientversion ?

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>wiki - The Ethereum Wiki - </div></blockquote>

2018-04-09 17:56 UTC, mandrigin commented
@ovx hey! thanks for your contribution.
sorry for making stuff a bit confusing in the issue description 😅 

can you, please, update your PR so it contains only this: `web3_clientversion` returns the current version and a revision (git commit sha) along another information.
example output is: `"result": "Status/v0.9.3-729b57db/darwin/go1.4.1"`

we reconsidered the approach, and I forgot to update the issue accordingly, sorry for that :(

2018-04-10 01:08 UTC, ovx commented
@mandrigin ok, no problem. If I understand it correctly, new RPC handler `web3_clientversion` needs to be registered here https://github.com/status-im/status-go/blob/develop/geth/api/backend.go#L262

2018-04-10 07:26 UTC, adambabik commented
@ovx `web3_clientversion` is already built-in so no need to register it. I believe what we need to do is to make sure the version passed here https://github.com/status-im/status-go/blob/02309e81e98bdda0317ed35b4c94a234d301ab90/geth/params/config.go#L319 (defined here https://github.com/status-im/status-go/blob/02309e81e98bdda0317ed35b4c94a234d301ab90/geth/params/version.go#L22) has the proper value. 

Git SHA is passed with [`BUILD_FLAGS`](https://github.com/status-im/status-go/blob/02309e81e98bdda0317ed35b4c94a234d301ab90/Makefile#L15), however, it overrides different vars. You need to pass different build tags to override `VersionMeta` in `geth/params` package. Don't care about `VersionMajor` etc. for now, just let's make sure `VersionMeta` has Git SHA value.

How to test it? First, build the binary: `make statusgo`, then run it: `./build/bin/statusd -http` and finally in a different terminal use curl:
```
curl -v -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"web3_clientVersion", "params": [], "id":1}' http://127.0.0.1:8545
```

2018-04-10 09:12 UTC, ovx commented
Fixed.

`statusd --version` output:

```
StatusIM
Version: 0.9.9-07298451
Git Commit: 07298451
...
    "Version": "0.9.9-07298451",
```

RPC output: 

```
{"jsonrpc":"2.0","id":1,"result":"StatusIM/v0.9.9-07298451/darwin-amd64/go1.10"}
```

2018-04-10 09:27 UTC, mandrigin approved these changes
Looks good! @adambabik?

2018-04-10 10:09 UTC, adambabik approved these changes
LGTM! Very nice and short solution!

2018-04-10 10:36 UTC, merged