Covered topic flags with tests
status-im/status-go pull request #808
Opened 2018-04-09 06:26 UTC by dshulyak

2018-04-09 17:30 UTC, mandrigin commented on Gopkg.lock
> +  inputs-digest = "2bdb7a811f635e7d86992a28dfa158f917167dd443bd5766945492c52bbd6534"
🤔

2018-04-09 17:31 UTC, mandrigin requested changes
the changes here look very similar to a peer pool. what is the difference?

2018-04-09 17:38 UTC, dshulyak commented
@mandrigin i just want to land more of the same code :)

i need to rebase. the difference is in cmd/topics/ module. there are new tests

2018-04-09 17:43 UTC, mandrigin commented
@dshulyak ah, sure! let's land the peer pool first (one conflict left) and then that'd be much easier to review this one :)

2018-04-10 09:11 UTC, dshulyak commented
@mandrigin rebased

2018-04-10 09:22 UTC, mandrigin approved these changes
Looks good!
I would also have a README.md in the `topics` package with a few examples and maybe a link to the unit-tests for more deep details.

2018-04-10 10:26 UTC, adambabik approved these changes

2018-04-10 13:18 UTC, merged